<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-03T16:09:04 SAST" name="Suite" finished-at="2025-07-03T16:15:16 SAST" duration-ms="372054">
    <groups>
    </groups>
    <test started-at="2025-07-03T16:09:04 SAST" name="Test" finished-at="2025-07-03T16:15:16 SAST" duration-ms="372054">
      <class name="com.dennismamyala.automation.My_First_Project.ErrorValidationTest">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:09:12 SAST" name="LaunchApplication" finished-at="2025-07-03T16:10:13 SAST" duration-ms="60651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="loginErrorValidation(java.util.HashMap)[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:10:13 SAST" name="loginErrorValidation" data-provider="getInvalidLoginData" finished-at="2025-07-03T16:10:19 SAST" duration-ms="6525" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{errorMessage=Login failed! Please ensure the username and password are valid., password=ThisIsNotAPassword, username=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:10:20 SAST" name="Close" finished-at="2025-07-03T16:10:24 SAST" duration-ms="4774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:10:24 SAST" name="LaunchApplication" finished-at="2025-07-03T16:10:52 SAST" duration-ms="27800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="loginErrorValidation(java.util.HashMap)[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:10:52 SAST" name="loginErrorValidation" data-provider="getInvalidLoginData" finished-at="2025-07-03T16:10:58 SAST" duration-ms="5883" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{errorMessage=Login failed! Please ensure the username and password are valid., password=, username=John Doe}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:10:58 SAST" name="Close" finished-at="2025-07-03T16:11:00 SAST" duration-ms="2160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:11:00 SAST" name="LaunchApplication" finished-at="2025-07-03T16:11:31 SAST" duration-ms="30550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="loginErrorValidation(java.util.HashMap)[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:11:31 SAST" name="loginErrorValidation" data-provider="getInvalidLoginData" finished-at="2025-07-03T16:11:37 SAST" duration-ms="5900" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{errorMessage=Login failed! Please ensure the username and password are valid., password=ThisIsNotAPassword, username=##123@}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:11:37 SAST" name="Close" finished-at="2025-07-03T16:11:38 SAST" duration-ms="944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:11:38 SAST" name="LaunchApplication" finished-at="2025-07-03T16:13:30 SAST" duration-ms="112570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method retried="true" signature="loginErrorValidation(java.util.HashMap)[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:13:30 SAST" name="loginErrorValidation" data-provider="getInvalidLoginData" finished-at="2025-07-03T16:13:37 SAST" duration-ms="6242" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{errorMessage=ogin failed! Please ensure the username and password are valid., password=&password@, username=John Doe}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at Utils.WebDriverUtils.assertEquals(WebDriverUtils.java:46)
at com.dennismamyala.automation.My_First_Project.Pages.Login_Page.hasErrorAppeared(Login_Page.java:63)
at com.dennismamyala.automation.My_First_Project.Base.BaseTest.hasErrorMessageAppeared(BaseTest.java:122)
at com.dennismamyala.automation.My_First_Project.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:13:37 SAST" name="Close" finished-at="2025-07-03T16:13:38 SAST" duration-ms="1592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:13:38 SAST" name="LaunchApplication" finished-at="2025-07-03T16:14:21 SAST" duration-ms="42649" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method retried="true" signature="loginErrorValidation(java.util.HashMap)[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:14:21 SAST" name="loginErrorValidation" data-provider="getInvalidLoginData" finished-at="2025-07-03T16:14:28 SAST" duration-ms="6915" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{errorMessage=ogin failed! Please ensure the username and password are valid., password=&password@, username=John Doe}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at Utils.WebDriverUtils.assertEquals(WebDriverUtils.java:46)
at com.dennismamyala.automation.My_First_Project.Pages.Login_Page.hasErrorAppeared(Login_Page.java:63)
at com.dennismamyala.automation.My_First_Project.Base.BaseTest.hasErrorMessageAppeared(BaseTest.java:122)
at com.dennismamyala.automation.My_First_Project.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:14:28 SAST" name="Close" finished-at="2025-07-03T16:14:30 SAST" duration-ms="2198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:14:30 SAST" name="LaunchApplication" finished-at="2025-07-03T16:14:57 SAST" duration-ms="27279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="loginErrorValidation(java.util.HashMap)[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:14:57 SAST" name="loginErrorValidation" data-provider="getInvalidLoginData" finished-at="2025-07-03T16:15:04 SAST" duration-ms="7086" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{errorMessage=ogin failed! Please ensure the username and password are valid., password=&password@, username=John Doe}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ogin failed! Please ensure the username and password are valid.] but found [Login failed! Please ensure the username and password are valid.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at Utils.WebDriverUtils.assertEquals(WebDriverUtils.java:46)
at com.dennismamyala.automation.My_First_Project.Pages.Login_Page.hasErrorAppeared(Login_Page.java:63)
at com.dennismamyala.automation.My_First_Project.Base.BaseTest.hasErrorMessageAppeared(BaseTest.java:122)
at com.dennismamyala.automation.My_First_Project.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.dennismamyala.automation.My_First_Project.ErrorValidationTest@36804139]" started-at="2025-07-03T16:15:13 SAST" name="Close" finished-at="2025-07-03T16:15:16 SAST" duration-ms="2999" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.dennismamyala.automation.My_First_Project.ErrorValidationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
